redis:
    extends:
        file: docker-compose-common.yml
        service: commonredis
    ports:
        - "127.0.0.1:6379:6379"
worker:
    extends:
        file: docker-compose-common.yml
        service: commonworker
    links:
        - redis
